config/routes.rb
Gayface::Application.routes.draw do

  resources :locations, :path => 'map'

  get "static_pages/home", :path => '/home'

  get "static_pages/about", :path => '/about'

  get "static_pages/events", :path => '/events'

  get "static_pages/contact", :path => '/contact'

  resources :users  #, :path => 

  get 'users/:id', to: 'users#show'

  get "gallery/index", :path => '/gallery'

  get 'users/index', :path => '/admin'

  root :to => 'static_pages#home'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :region, :user_location

  def region_on_map
    @region_on_map = User.state.upcase
  end 

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :blurb, :city, :first_name, :image_url, :last_name, :occupation, :sexuality, :state

  validates :city, :first_name, :image_url, :last_name, :occupation, :sexuality, :state, presence: true

  validates :image_url, allow_blank: true, format: {
  with: %r{\.(gif|jpg|png)\Z}i,
  message: 'must be a URL for GIF, JPG or PNG image.'
  }

  def full_name
    [first_name, last_name].join(" ")
  end

  def location
    [city, state].join(", ")
  end

end



  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
    @users = User.order(:state)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def events
  end

  def contact
  end

  def user
  end 


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  
end

app/views/gallery/index.html.erb
<%= javascript_include_tag "http://code.jquery.com/jquery-1.9.1.min.js" %>
<%= javascript_include_tag "masonry.pkgd.min.js" %>  

<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<div class="fullscreen_block" style="padding-top: 69px; min-height: 840px;">

<!-- FILTER NAV -->
  <div class="filter_block">
      <div class="filter_navigation">
          <!-- <ul id="options" class="splitter">
              <li>
                  <ul data-option-key="filter" class="optionset">
                      <li class="selected"><a data-option-value="*" href="#filter">All Locations</a></li>
                      <li><a title="View all the Gay Faces from NYC" data-option-value=".portraits" href="#filter">New York</a></li>
                      <li><a title="VView all the Gay Faces from LA" data-option-value=".fashion" href="#filter">Los Angeles</a></li>
                      <li><a title="View all the Gay Faces from New Jerset" data-option-value=".stories" href="#filter">NJ</a></li>
                      <li><a title="View all the Gay Faces from San Francisco" data-option-value=".fashion" href="#filter">San Fran</a></li>
                  </ul>
              </li>
          </ul> -->
      </div><!-- .filter_navigation -->
  </div><!-- .filter_block -->
<!-- END FILTER NAV -->

  <div class="fs_grid_module" style="min-height: 582px; position: relative; height: 1760px;">
      
<!-- USER/IMAGE BLOCK. ITERATE OVER USERS TO GET ALL USERS'S PHOTOS AND PLOP THEM IN THE DESIGN LAYOUT -->
<!-- WILL NEED FILTERING/PAGINATION -->
  <% @users.each do |user| %>

    <div class="grid_gallery-item" data-top="-80px" style="opacity: 1; position: absolute; left: 0px; top: 0px;">
      <div class="item_hover" style="top: 0px;">
        <div class="item_hover-img">
          <%#= image_tag user.image_url %>
          <%= link_to image_tag(user.image_url, :class => "prettyPhoto", :rel => "prettyPhoto[gallery1]"), user %>
            <div class="item_hover-fadder"></div>
              <!-- <a href="img/gallery/gallery_grid1-1.jpg" rel="prettyPhoto[gallery1]" class="prettyPhoto"></a> --><!-- <a href="portfolio_post.html" class="post_link"></a> -->
        </div>
        <div class="item_hover-body">
            <div class="item_hover-descr">
                <h5><%= link_to user.full_name, user %></h5>
                <p><%= user.location %></p>
            </div>
        </div>
      </div>
    </div>

  <% end %>
<!-- END USER IMAGE BLOCK -->

  <div class="clear"></div>
  </div><!-- .fs_grid_module -->
</div> <!-- .fullscreen_block -->   
<!-- END TOP  -->

<div class="header2top"></div>
    <!--<div class="header2top"></div>-->


<script>
  $(document).ready(function(){
  });
  $(window).load(function(){
    //$('.fs_grid_module').masonry();
    $('.fs_grid_module').masonry({
      itemSelector: '.grid_gallery-item',
      isAnimated: true
    });
    setTimeout("$('.fs_grid_module').masonry()",500);
  });
  $(window).resize(function(){
    $('.fs_grid_module').masonry();
  });
</script>

<%= javascript_include_tag "http://code.jquery.com/ui/1.10.2/jquery-ui.min.js" %>
<%= javascript_include_tag "theme.js" %>    

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<p style="text-transform:capitalize;">
  Copyright, 2013, GayFace. All Rights Reserved. 
  <br>  
<!--   Designed and Developed by The Machine Elf, LLC  -->
</p> 

app/views/layouts/_nav.html.erb
<header class="">
  <div class="header_wrapper container">

    <%= link_to(image_tag('logo.jpg', :class => "logo", :width => "200", :height => "60"), static_pages_home_path) %>
  
      <nav>
          <ul class="menu">
              <li> <%= link_to "HOME", static_pages_home_path %> </li>
              <li> <%= link_to "GALLERY", gallery_index_path %> </li>
              <li> <%= link_to "MAP", locations_path %> </li>
              <li> <%= link_to "EVENTS", static_pages_events_path %> </li>
              <li> <%#= link_to "FORUM", static_pages_home_path %> </li>
              <li> <%#= link_to "SHOP", static_pages_home_path %> </li>
               <li> <%= link_to "ABOUT", static_pages_about_path %> </li>
              <li> <%= link_to "CONTACT", static_pages_contact_path %> </li>
          </ul>
              
          <div class="clear"></div>
      </nav>
  </div>
</header>

app/views/layouts/_social_links.html.erb
<footer>
    <div class="footer_line container">
        <div class="socials">
          <ul class="socials_list">
              <li><a href="#" class="ico_social-facebook"></a></li>
              <%#= image_tag "frame_icons.png", :class "ico_social-twitter" %>
                <li><a href="#" class="ico_social-twitter"></a></li>
                <li><a href="#" class="ico_social-linked"></a></li>
                <li><a href="#" class="ico_social-delicious"></a></li>
                <li><a href="#" class="ico_social-vimeo"></a></li>
                <li><a href="#" class="ico_social-flickr"></a></li>
                <li><a href="#" class="ico_social-pinterest"></a></li>
                <li><a href="#" class="ico_social-tumblr"></a></li>                   
                <li><a href="#" class="ico_social-youtube"></a></li>                    
                <li><a href="#" class="ico_social-instagram"></a></li>
                <li><a href="#" class="ico_social-gplus"></a></li>
                <li><a href="#" class="ico_social-dribbble"></a></li>
            </ul>            
        </div>
      
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!-- HEAD -->
<head>
<meta charset="utf-8">
<title>Gayface</title> 
<meta name="description" content="Gayface"/>
<meta name="keywords" content="Gayface" />
<meta name="author" content="Designed and Developed for Gayface by Samantha Radocchia aka iamsamsterdam. The Machine Elf, LLC."/>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<!-- END HEAD -->

<body> <!-- class="fullscreen_layout" just in case i need this part? -->

<!-- NAVIGATION BAR -->
<%= render "layouts/nav" %>
<!-- END NAVIGATION -->
<%= yield %>


</body>


<footer>
  <%= render "layouts/footer" %>
</footer>

</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_location %><br />
    <%= f.text_field :user_location %>
  </div>
  <div class="field">
    <%= f.label :region %><br />
    <%= f.text_field :region %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<!-- #################################################################
<title>JQVMap - World Map</title> -->
<%= stylesheet_link_tag "jqvmap" %>
<%= javascript_include_tag "jquery.vmap.js" %>  
<%= javascript_include_tag "jquery.vmap.usa.js" %>  

    <script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#vmap').vectorMap(
        { 
            map: 'usa_en',
            backgroundColor: '#ffffff', 
            enableZoom: true, 
            hoverColor: '#000000',
            hoverOpacity: null,
            selectedColor: '#545454',
            selectedRegion: null,

            onRegionClick: function(element, code, region)
    {
        var message = 'You clicked "'
            + region 
            + '" which has the code: '
            + code.toUpperCase();
             
        alert(message);
    }
        });

// SETS COLORS OF STATES TO DIFFERENT COLORS BASED ON WHETHER THE 
// STATE HAS GAYFACE USERS OR NOT

// need to add if-else statement that sets colors 
        jQuery('#vmap').vectorMap('set', 'colors', {al: 'red'});
        jQuery('#vmap').vectorMap('set', 'colors', {ak: 'red'});
        jQuery('#vmap').vectorMap('set', 'colors', {az: 'red'});
        jQuery('#vmap').vectorMap('set', 'colors', {ar: 'red'});

    });
    </script>
  



    <div id="vmap" style="width: 600px; height: 400px;"></div>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User location:</b>
  <%= @location.user_location %>
</p>

<p>
  <b>Region:</b>
  <%= @location.region %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/static_pages/about.html.erb
<%= javascript_include_tag "http://code.jquery.com/jquery-1.9.1.min.js" %> 

<div class="fullscreen_block">
      <div class="fullscreen_title">
          <h1>About</h1>
          <a href="javascript:history.back()" class="btn_close"></a>
            <!--<a href="#" class="btn_next"></a>
            <a href="#" class="btn_prev"></a>-->
        </div>

      <div class="fullscreen_content_wrapper">
            <div class="featured_slider_wrapper fullscreen_container">
              <a href="javascript:void(0)" class="featured_prev"></a><a href="javascript:void(0)" class="featured_next"></a>
              <ul class="featured_slider-list">
                  <li><%= image_tag("ash1.jpg") %></li>
                  <li><%#= image_tag("ash2.jpg") %></li>
                </ul>
            </div>
        </div><!-- .fullscreen_content_wrapper -->

        <div class="fullscreen_content">
            <a href="javascript:void(0)" class="content_toggle"><span class="collapse">Collapse</span><span class="show">Show info</span></a>        
            <div class="fullscreen_content_padding">
                <div class="row-fluid">
                    <div class="span12 module_cont module_fs_meta module_none_padding">
                        <p><span>25 April 2019</span> in <a href="#">Category</a></p>
                        <p><span>Author:</span> John Doe</p>
                        <p><span>Tags:</span> <a href="#">lorem</a>, <a href="#">ipsum</a>, <a href="#">dolor</a>, <a href="#">sit amet</a>, <a href="#">egestas</a></p>
                    </div>                
                </div><!-- .row-fluid -->

                <div class="row-fluid">
                    <div class="span12 module_cont module_contact_icons module_small_padding1">
                        <a href="#" class="ico_socialize_facebook1 ico_socialize type1"></a>
                        <a href="#" class="ico_socialize_twitter2 ico_socialize type1"></a>
                        <a href="#" class="ico_socialize_pinterest ico_socialize type1"></a>
                        <a href="#" class="ico_socialize_google2 ico_socialize type1"></a>
                    </div>
                </div><!-- .row-fluid -->                    

                <div class="row-fluid">
                    <div class="span12 module_cont module_text_area module_small_padding">
                        <p>Class aptent taciti sociosqu ad litora torquent per conubia ostras per inceptos himenaeos. In vehicula placerat pharetra.</p>
                        <p>Pellentesque vestibulum erat eu libero viverra consectetur ac eget turpis. Pellentesque magna enim, iaculis ut eleifend egetus nec ligula. Nullam mollis posuere libero, 
                        vitae porta magna fringilla vitae. Quisque ullamcorper nulla nec tortor vehicula vele <a href="#">aliquet nibh</a> dignissim. Mauris non ligula augue, ac laoreet antet fusce enim magna, 
                        tempus quis lobortis eu, pharetra eu ligula.</p>
                        <p>Nullam eu lacus neque, ut vulputate nulla. Morbi a felis a nunc viverra placerat. Curabitur molestie erat fermentum nibh suscipit dictum. Nullam eget augue sit amet velit 
                        adipiscing malesuada vel in mauris. Mauris egestas sodales felis vel faucibus. Aliquam vehicula nisi vel enim dapibus tempor. Cras rutrum quam at tem cursus a porta lorem luctus. 
                        Fusce vitae dolor in turpis posuere rhoncus sed ac m praesent venenatis, faucibus a varius lobortis ante id eros luctus consequat eget augue sit amet velit. Mauris nisi lectus, 
                        sollicitudin ac pulvinar nec, pulvinar ac odio. Nunc semper dignissim vehicula. Nunc id lorem nec quam facilisis tincidunt. Phasellus nec urna in odio sollicitudin faucibus 
                        sed tristique ligula. Fusce accumsan varius libero. Proin vitae velit a purus pulvinar cursus eu a erat. Donec molestie tempor eros faucibus porttitor.</p>
                        <p>Fusce dui enim, mattis id suscipit nec, posuere a augue sodales sapien sit amet justo ultricies <a href="#">ultrices pretium.</a></p>
                    </div>                
                </div><!-- .row-fluid -->

            </div><!-- .fullscreen_content_padding -->
        </div><!-- .fullscreen_content -->
        
  </div>    
    <div class="header2top"></div>
    
 <%= javascript_include_tag "http://code.jquery.com/ui/1.10.2/jquery-ui.min.js" %> 
 <%= javascript_include_tag "theme.js" %>    
 

app/views/static_pages/home.html.erb
<%= javascript_include_tag "http://code.jquery.com/jquery-1.9.1.min.js" %>
<%= javascript_include_tag "fs_gallery.js" %>  


<body class="fullscreen_layout">
  <div class="fullscreen_block"></div>    
    <script>
    gallery_set = [ //Gallery Data

      // THIS IS AN EXAMPLE IN CASE I WANT TO BRING BACK THE NAME/TAGLINE HOVER

      // {image : "<%= asset_path('test1.jpg') %>", alt : 'Ahi', fit : 'cover', title : "find a way to put username in here", description: "right here we've got something you gonna love..."},

      {image : "<%= asset_path('home/home1.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home2.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home3') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home4.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home5.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home6.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home7.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home8.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home9.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home10.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home11.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home12.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home13.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home14.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home15.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home16.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home17.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home18.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home19.jpg') %>", fit : 'cover'},
      {image : "<%= asset_path('home/home20.jpg') %>", fit : 'cover'}    
    ];
    $('body').fs_gallery({
      fx : 'fade', /*fade, zoom, slide_left, slide_right, slide_top, slide_bottom*/
      slide_time : 3300, /*This time must be < then time in css*/
      slides : gallery_set
    });
  </script>

  <%= javascript_include_tag "http://code.jquery.com/ui/1.10.2/jquery-ui.min.js" %>
  <%= javascript_include_tag "theme.js" %>  
 
  <div class="header2top"></div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <br>
  <br>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :sexuality %><br />
    <%= f.text_field :sexuality %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :occupation %><br />
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :blurb %><br />
    <%= f.text_area :blurb, rows: 6 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
 <div class="main_wrapper">
        <!-- C O N T E N T -->
        <div class="content_wrapper">
              <div class="container">

  <table>
<% @users.each do |user| %>
  <tr>
    <td>First Name<%= user.first_name %></td>
    <td>Last Name <%= user.last_name %></td>
    <td>Photo <%= image_tag(user.image_url, :width => "300px") %></td>
    <td>Sexuality<%= user.sexuality %></td>
    <td>City<%= user.city %></td>
    <td>State<%= user.state %></td>
    <td>Occupation<%= user.occupation %></td>
    <td>Blurb<%= truncate(strip_tags(user.blurb), length: 140) %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

 
  <div class="header2top"></div>
</div>
</div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
 <div class="main_wrapper">
        <!-- C O N T E N T -->
        <div class="content_wrapper">
              <div class="container">


<p id="notice"><%= notice %></p>

<!-- GAYFACE PHOTO -->
<%= image_tag(@user.image_url, :width => "100%", :height => "auto") %>

<!-- USER'S FIRST NAME -->
<%#= @user.first_name %>

<!-- USER'S LAST NAME -->
<%#= @user.last_name %>

<!-- USER'S FULL NAME (First and Last Initial) -->
<h1>
  <%= @user.first_name %> <%= @user.last_name.chars.first %>
</h1>

<!-- SEXUAL IDENTIFICATION (How they Identify) -->
<p>
  <b>Identifies As:</b>
  <%= @user.sexuality %>
</p>

<!-- CITY -->
<%#= @user.city %>

<!-- STATE -->
<%#= @user.state %>

<!-- CITY, STATE  -->
<p>
  <b> Location: </b>
<%= @user.city %>, <%= @user.state.upcase %>
</p>

<!-- OCCUPATION -->
<p>
  <b>Occupation:</b>
  <%= @user.occupation %>
</p>

<!-- BLURB -->
<p>
  <b>Blurb</b>
  <br>
  <%= truncate(strip_tags(@user.blurb), length: 250) %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |



</div>
</div>
</div>